// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvxPNhYR4b9C7MS-mr3tDpTM1WiYF5vkY',
    appId: '1:303940029661:web:71a42f37794985df1d1f34',
    messagingSenderId: '303940029661',
    projectId: 'chatapp-2fc3d',
    authDomain: 'chatapp-2fc3d.firebaseapp.com',
    databaseURL: 'https://chatapp-2fc3d-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2fc3d.appspot.com',
    measurementId: 'G-YBZQTQE3XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeqAprvLa46YqbTqwCHZTASazE_dkDQ-4',
    appId: '1:303940029661:android:e9743b61a75d70e01d1f34',
    messagingSenderId: '303940029661',
    projectId: 'chatapp-2fc3d',
    databaseURL: 'https://chatapp-2fc3d-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2fc3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlaxYnXWgtb4baRPZMByF1a-U9-Tcju8o',
    appId: '1:303940029661:ios:5fd541a435e7d13e1d1f34',
    messagingSenderId: '303940029661',
    projectId: 'chatapp-2fc3d',
    databaseURL: 'https://chatapp-2fc3d-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2fc3d.appspot.com',
    iosClientId: '303940029661-sl1ethd68n6te5jas82o0vsn1ls4bmna.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlaxYnXWgtb4baRPZMByF1a-U9-Tcju8o',
    appId: '1:303940029661:ios:5fd541a435e7d13e1d1f34',
    messagingSenderId: '303940029661',
    projectId: 'chatapp-2fc3d',
    databaseURL: 'https://chatapp-2fc3d-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2fc3d.appspot.com',
    iosClientId: '303940029661-sl1ethd68n6te5jas82o0vsn1ls4bmna.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
