// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4V-LemRW2syrf2sMQVzp0Pb9MAo95O9I',
    appId: '1:32903398845:web:bf3949975ce0e21f943ed4',
    messagingSenderId: '32903398845',
    projectId: 'binder-app-3b8de',
    authDomain: 'binder-app-3b8de.firebaseapp.com',
    storageBucket: 'binder-app-3b8de.appspot.com',
    measurementId: 'G-M2Z2CS2PVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvDYqP4XFvQtF2gB-nljIt-Q_pgRdoEGM',
    appId: '1:32903398845:android:973311cc9f97c01a943ed4',
    messagingSenderId: '32903398845',
    projectId: 'binder-app-3b8de',
    storageBucket: 'binder-app-3b8de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwZZKmp2m5ScUF5G5aTqYT_MC_eLoJys',
    appId: '1:32903398845:ios:55b9df6459bb2f05943ed4',
    messagingSenderId: '32903398845',
    projectId: 'binder-app-3b8de',
    storageBucket: 'binder-app-3b8de.appspot.com',
    iosClientId: '32903398845-qgv4m7ergep2f3fls72g29tgf6q9o0mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCwZZKmp2m5ScUF5G5aTqYT_MC_eLoJys',
    appId: '1:32903398845:ios:55b9df6459bb2f05943ed4',
    messagingSenderId: '32903398845',
    projectId: 'binder-app-3b8de',
    storageBucket: 'binder-app-3b8de.appspot.com',
    iosClientId: '32903398845-qgv4m7ergep2f3fls72g29tgf6q9o0mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
